ImprovingCore/Globomantics/Controllers/LoanController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Globomantics.Models;
using Globomantics.Services;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Http;

namespace Globomantics.Controllers
{
    public class LoanController : Controller
    {
        private ILoanService loanService;

        public LoanController(ILoanService loanService)
        {
            this.loanService = loanService;
        }

        public IActionResult Application()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Application(LoanDetails app)
        {
            if (ModelState.IsValid)
            {
                loanService.CreateLoanApplication(app, Guid.NewGuid().ToString());
                return RedirectToAction("Employment");
            }

            return View(app);
        }

        [HttpGet]
        public IActionResult Employment()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Employment(Employment employment)
        {
            if (ModelState.IsValid)
            {
                loanService.UpdateLoanEmployment(employment);
                return RedirectToAction("Personal");
            }

            return View(employment);
        }

        [HttpGet]
        public IActionResult Personal()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Personal(Person person)
        {
            if (ModelState.IsValid)
            {
                loanService.UpdateLoanPersonalInfo(person);
                return RedirectToAction("Confirmation");
            }

            return View(person);
        }

        [HttpGet]
        public IActionResult Confirmation()
        {
            var loan = loanService.GetConfirmationDetails();
            return View(loan);
        }

        [HttpGet]
        public IActionResult Success()
        {
            return View();
        }
    }
}

ImprovingCore/Globomantics/Views/Loan/Application.cshtml
@model LoanDetails

    @section Banner {
        <div class="jumbotron jumbotron-fluid jumbotron-blue">
            <div class="container">
                <h1 class="display-4">Request a Loan</h1>
                <p class="lead">Kickstart your dream today.</p>
            </div>
        </div>
    }

    @section SideNav {
        <p class="lead">Loan Application Progress</p>
        <div class="list-group">
            <button type="button" class="list-group-item list-group-item-action active">Loan Info</button>
            <button type="button" class="list-group-item list-group-item-action" disabled>Employment Info</button>
            <button type="button" class="list-group-item list-group-item-action" disabled>Personal Info</button>
            <button type="button" class="list-group-item list-group-item-action" disabled>Confirmation</button>
        </div>
    }

    <h2>Loan Details</h2>
    <p>Let us know what type of loan you're looking for.</p>
    <form method="post" asp-controller="Loan" asp-action="Application">
        <hr class="featurette-divider-thin">

        <div class="form-group">
            <label asp-for="Type">Loan Type</label>
            <select asp-for="Type" class="form-control">
                <option>Auto Loan</option>
                <option>Personal Loan</option>
                <option>School Loan</option>
            </select>
        </div>
        <div class="form-group">
            <label asp-validation-for="Amount" asp-for="Amount">Loan Amount</label>
            <input asp-for="Amount" type="text" class="form-control" placeholder="Loan Amount">
            <span asp-validation-for="Amount" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="TermLength">Desired Term Length (Months)</label>
            <select asp-for="TermLength" class="form-control">
                <option>12</option>
                <option>24</option>
                <option>36</option>
                <option>48</option>
                <option>60</option>
            </select>
        </div>
        <div class="form-group">
            <label asp-for="IsSecured">Will the Loan be Secured with Collateral?</label>
            <select asp-for="IsSecured" class="form-control">
                <option>True</option>
                <option>False</option>
            </select>
        </div>

        <div class="form-group">
            <button class="btn btn-primary float-right">Next</button>
        </div>
    </form>

ImprovingCore/Globomantics/Views/Loan/Confirmation.cshtml
@model LoanApplication

@section Banner {
    <div class="jumbotron jumbotron-fluid jumbotron-blue">
        <div class="container">
            <h1 class="display-4">Confirmation</h1>
            <p class="lead">Your loan is just a click away.</p>
        </div>
    </div>
}

@section SideNav {
    <p class="lead">Loan Application Progress</p>
    <div class="list-group">
        <button type="button" class="list-group-item list-group-item-action" disabled>Loan Info</button>
        <button type="button" class="list-group-item list-group-item-action" disabled>Employment Info</button>
        <button type="button" class="list-group-item list-group-item-action">Personal Info</button>
        <button type="button" class="list-group-item list-group-item-action active" disabled>Confirmation</button>
    </div>
}
<h2>Summary</h2>
<hr class="featurette-divider-thin">
<p class="lead">Loan Details</p>
<table class="table table-bordered">
    <tbody>
        <tr>
            <th scope="row">Loan Type</th>
            <td asp-for="">@Model.LoanInfo.Type</td>
        </tr>
        <tr>
            <th scope="row">Loan Amount</th>
            <td>@Model.LoanInfo.Amount</td>
        </tr>
        <tr>
            <th scope="row">Term Length</th>
            <td>@Model.LoanInfo.TermLength</td>
        </tr>
        <tr>
            <th scope="row">Is Secured</th>
            <td>@Model.LoanInfo.IsSecured</td>
        </tr>
    </tbody>
</table>
<hr class="featurette-divider-thin">
<p class="lead">Employment Details</p>
<table class="table table-bordered">
    <tbody>
        <tr>
            <th scope="row">Employment Type</th>
            <td asp-for="">@Model.EmploymentInfo.Type</td>
        </tr>
        <tr>
            <th scope="row">Employer</th>
            <td>@Model.EmploymentInfo.EmployerName</td>
        </tr>
        <tr>
            <th scope="row">Income</th>
            <td>@Model.EmploymentInfo.AnnualIncome</td>
        </tr>
        <tr>
            <th scope="row">Length of Employment</th>
            <td>@Model.EmploymentInfo.Duration</td>
        </tr>
    </tbody>
</table>
<hr class="featurette-divider-thin">
<p class="lead">Personal Details</p>
<table class="table table-bordered">
    <tbody>
        <tr>
            <th scope="row">First Name</th>
            <td asp-for="">@Model.PersonalInfo.FirstName</td>
        </tr>
        <tr>
            <th scope="row">Last Name</th>
            <td>@Model.PersonalInfo.LastName</td>
        </tr>
        <tr>
            <th scope="row">Date of Birth</th>
            <td>@Model.PersonalInfo.Dob</td>
        </tr>
        <tr>
            <th scope="row">Email</th>
            <td>@Model.PersonalInfo.Email</td>
        </tr>
        <tr>
            <th scope="row">Phone</th>
            <td>@Model.PersonalInfo.Phone</td>
        </tr>
        <tr>
            <th scope="row">Address</th>
            <td>@Model.PersonalInfo.Street</td>
        </tr>
        <tr>
            <th scope="row">City</th>
            <td>@Model.PersonalInfo.City</td>
        </tr>
        <tr>
            <th scope="row">State</th>
            <td>@Model.PersonalInfo.State</td>
        </tr>
        <tr>
            <th scope="row">Zip</th>
            <td>@Model.PersonalInfo.Zip</td>
        </tr>
    </tbody>
</table>

<div class="form-group">
    <button class="btn btn-primary float-right">Confirm & Submit</button>
</div>

ImprovingCore/Globomantics/Views/Loan/Employment.cshtml
@model Employment

@section Banner {
    <div class="jumbotron jumbotron-fluid jumbotron-blue">
        <div class="container">
            <h1 class="display-4">Knowledge is Power</h1>
            <p class="lead">We offer you the tools and education you need to succeed.</p>
        </div>
    </div>
}

@section SideNav {
    <p class="lead">Loan Application Progress</p>
    <div class="list-group">
        <button type="button" class="list-group-item list-group-item-action" disabled>Loan Info</button>
        <button type="button" class="list-group-item list-group-item-action active">Employment Info</button>
        <button type="button" class="list-group-item list-group-item-action" disabled>Personal Info</button>
        <button type="button" class="list-group-item list-group-item-action" disabled>Confirmation</button>
    </div>
}

<h2>Employment Info</h2>
<p>Please provide information about your employment.</p>
<form method="post" asp-controller="Loan" asp-action="Employment">
    <hr class="featurette-divider-thin">

    <div class="form-group">
        <label>Current Employment Type</label>
        <select asp-for="CurrentType" class="form-control">
            <option val="Full Time">Full Time</option>
            <option val="Part Time">Part Time</option>
            <option val="Variable">Variable</option>
            <option val="Unemployed">Unemployed</option>
        </select>
    </div>
    <div class="form-group">
        <label>Current Employer</label>
        <input asp-for="CurrentEmployerName" type="text" class="form-control" placeholder="Employer Name">
    </div>
    <div class="form-group">
        <label>Current Annual Income</label>
        <input asp-for="CurrentAnnualIncome" type="text" class="form-control" placeholder="Annual Income">
    </div>
    <div class="form-group">
        <label>Length of Time at Current Employer</label>
        <select id="employmentLength" asp-for="CurrentDuration" class="form-control">
            <option value="1">Select</option>
            <option value="1">Less Than 2 Years</option>
            <option value="3">2-5 Years</option>
            <option value="5">5+ Years</option>
        </select>
    </div>


    <!-- If less than 2 years -->
    <div id="previousEmployment" style="display: none">
        <hr class="featurette-divider-thin">
        <h2>Previous Employment</h2>
        <div class="form-group">
            <label>Previous Employment Type</label>
            <select asp-for="PreviousType" class="form-control">
                <option>Full Time</option>
                <option>Part Time</option>
                <option>Variable</option>
                <option>Unemployed</option>
            </select>
        </div>
        <div class="form-group">
            <label>Previous Employer</label>
            <input asp-for="PreviousEmployerName" type="text" class="form-control" placeholder="Employer Name">
        </div>
        <div class="form-group">
            <label>Previous Annual Income</label>
            <input asp-for="PreviousAnnualIncome" type="text" class="form-control" placeholder="Annual Income">
        </div>
        <div class="form-group">
            <label>Length of Time at Previous Employer</label>
            <input asp-for="PreviousDuration" type="text" class="form-control" placeholder="Employment Duration">
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-primary float-right">Submit</button>
    </div>
</form>

ImprovingCore/Globomantics/Views/Loan/Personal.cshtml
@model AutoQuote

@section Banner {
    <div class="jumbotron jumbotron-fluid jumbotron-blue">
        <div class="container">
            <h1 class="display-4">Knowledge is Power</h1>
            <p class="lead">We offer you the tools and education you need to succeed.</p>
        </div>
    </div>
}

@section SideNav {
    <p class="lead">Loan Application Progress</p>
    <div class="list-group">
        <button type="button" class="list-group-item list-group-item-action" disabled>Loan Info</button>
        <button type="button" class="list-group-item list-group-item-action" disabled>Employment Info</button>
        <button type="button" class="list-group-item list-group-item-action active">Personal Info</button>
        <button type="button" class="list-group-item list-group-item-action" disabled>Confirmation</button>
    </div>
}

<h2>Personal Info</h2>
<p>Let us know more about yourself.</p>
<form method="post" asp-controller="Loan" asp-action="Personal">

    @Html.Partial("Person")

    <div class="form-group">
        <button class="btn btn-primary float-right">Submit</button>
    </div>
</form>